### PR TITLE
remove files created by setup.py

### PR DESCRIPTION
**Pull request by jdelic**
This PR removes all files under `build/` which shouldn't in the repo since they're temporary files created during packaging by setup.py

### CODE REVIEW

**Comment by geneshuman** [comment]
Hi!  I just wanted to checkin about these patches you've submitted.  This repo isn't the official one (thats on launchpad), its just a fork we made for development of a major feature.  It's probably not going to be updated often, as I'm not sure I want to be responsible for manually syncing between this & the bzr repo.

**Comment by jdelic** [comment]
@geneshuman 
> Hi! I just wanted to checkin about these patches you've submitted. This repo isn't the official one (thats on launchpad), its just a fork we made for development of a major feature. It's probably not going to be updated often, as I'm not sure I want to be responsible for manually syncing between this & the bzr repo.

I understand that this is the source of the ARC implementation. It also seems to be the source of the official 0.6.1 release to the Cheeseshop.

The bugfixes I opened as a PR against this repository are fixes that have been on the official tracker for over a year and have also been successfully ignored by upstream. I updated [my unofficial fork](https://pypi.python.org/pypi/mn-dkimpy) with these fixes to avoid regressions in my own codebase and thought I'd make it easy for you to assemble 0.6.2 to finally get these fixes out there :). In any case all of the bugfixes I submitted as PRs (aside from this one, which is really just code hygiene) have been filed (with patches) against dkimpy in February 2016 in [bug 1542245](https://bugs.launchpad.net/dkimpy/+bug/1542245), [bug 1541343](https://bugs.launchpad.net/dkimpy/+bug/1541343) and [bug 1541341](https://bugs.launchpad.net/dkimpy/+bug/1541341).

I would just really like to see them fixed so I can switch back to the official release at some point.

**Comment by geneshuman** [comment]
OK cool, I'm going to accept these PR's, and get them all merged upstream into the launchpad repo for you.  After than they should be in PyPI.  Might take a few days.

**Comment by jdelic** [comment]
> OK cool, I'm going to accept these PR's, and get them all merged upstream into the launchpad repo for you. After than they should be in PyPI. Might take a few days.

awesome, thank you 👍

**Pull request merged**
